### ISSUE TITLE
Upstream efforts

### ISSUE THREAD

**Issue by auscompgeek** [wozeparrot/rbot#2]
Hey @wozeparrot - found this repo and wanted to reach out.

A bunch of us are trying to gather our collective efforts over at @first-rust-competition. I've gotten in touch with @Lytigas to hopefully get the first-rust-competition monorepo moved across.

It'd be great if we could all continue our efforts together. Thoughts?

**Comment by wozeparrot** [comment]
I would love to help, this monorepo is still a work in progress, I don't know if we are going to go in the same direction, as I want to move away from wpilib style. Not sure about you.

**Comment by wozeparrot** [comment]
Also, I'm not sure if first-rust-competiton will still work in the 2020 season as I had to make a lot of changes in order to get  everything to function properly.

**Comment by auscompgeek** [comment]
I definitely want to see more idiomatic Rust. Some of the current design I want to see scrapped completely.

Aside from the new libraries to link against, I don't see any particular reason why first-rust-competition wouldn't work on the 2020 image.

**Comment by wozeparrot** [comment]
When I was creating rbot, I saw that they moved some stuff around with the libraries moved out of allwpilib. Some other small changes have to be done for it to work.

**Comment by auscompgeek** [comment]
I think the Gradle-based builds are rather heavy-handed for what we need to do anyway - we only need the HAL and its dependencies.

Either way, I believe that task still exists when skipping athena.

**Comment by wozeparrot** [comment]
No, I tried the task and it does not exist. Its not `:hal:halLinuxathenaReleaseSharedLibrary` to build hal for athena.

**Comment by auscompgeek** [comment]
WPILib's build logs indicate `:hal:halDebugSharedLibrary` and `:hal:halReleaseSharedLibrary` are still things.

**Comment by auscompgeek** [comment]
Either way, I see no reason to build WPILib ourselves in the first place.

**Comment by wozeparrot** [comment]
Yea, but we are not building WPILib we are only building hal.

**Comment by auscompgeek** [comment]
My point still stands.

**Comment by wozeparrot** [comment]
True, I am building it so that I can test that stuff links properly.

**Comment by auscompgeek** [comment]
You can just simply link to the libraries to do that?

**Comment by wozeparrot** [comment]
No because the libraries are not there. You have to compile them.

**Comment by auscompgeek** [comment]
They have already been compiled for you.

**Comment by wozeparrot** [comment]
where?
